Add explicit constructor
vidstige/jadb pull request #148
Opened 2022-03-23 17:49 UTC by adamoutler

Fixes a message with this class when modularized
se/vidstige/jadb/Subprocess.java:[23,8] class se.vidstige.jadb.Subprocess in exported package se.vidstige.jadb declares no explicit constructors, thereby exposing a default constructor to clients of module my.module.

2022-03-29 19:31 UTC, vidstige commented
Thanks for your contribution. The warning seems weird, where did you see this warning?

2022-03-30 00:24 UTC, adamoutler commented
Java 11.   I converted,  modularized, and imported to my codebase before you added the changes for automodule.  I'm contributing back compatible changes.   

You will eventually want to upgrade to Java 11, even if only in a docker container on Actions on GitHub.  Minor changes are needed for compatibility and  like this, but the major item is the module-info.java.  Aside from the module-info, it's just a bunch of lint and syntactic faux pas that have no bearing on operation, but make it more compatible with lint checks.

2022-03-31 08:11 UTC, vidstige commented
I see. Thanks for the initiative and your contribution. I'm currently not working _at all_ on this so any moves to new Java versions is entirely dependent on contributors like yourself. PRs welcome!

For the future - Avoid comments that are not very helpful like `// empty` to keep the code clean and easy to read.

2022-03-31 08:13 UTC, vidstige requested changes
I think the `public Subprocess(){}` constructor needs to be inside the `class Subprocess`? The build is currently failing.

Please amend the commit. :pray:

2025-03-05 21:12 UTC, closed without merging

2025-03-05 21:12 UTC, vidstige commented
Closing due to inactivity